# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/duza/studia/sem8/SR/SR_PROJ/trunk/window.ui'
#
# Created: Fri Dec  3 10:24:58 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(746, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Android-Messages-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitterLeftRight = QtGui.QSplitter(self.centralwidget)
        self.splitterLeftRight.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitterLeftRight.setOrientation(QtCore.Qt.Vertical)
        self.splitterLeftRight.setHandleWidth(10)
        self.splitterLeftRight.setObjectName(_fromUtf8("splitterLeftRight"))
        self.layoutWidget = QtGui.QWidget(self.splitterLeftRight)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitterUpDown = QtGui.QSplitter(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterUpDown.sizePolicy().hasHeightForWidth())
        self.splitterUpDown.setSizePolicy(sizePolicy)
        self.splitterUpDown.setMinimumSize(QtCore.QSize(0, 100))
        self.splitterUpDown.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitterUpDown.setFrameShadow(QtGui.QFrame.Raised)
        self.splitterUpDown.setOrientation(QtCore.Qt.Horizontal)
        self.splitterUpDown.setOpaqueResize(True)
        self.splitterUpDown.setHandleWidth(10)
        self.splitterUpDown.setObjectName(_fromUtf8("splitterUpDown"))
        self.layoutWidget1 = QtGui.QWidget(self.splitterUpDown)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.conversationView = QtGui.QTableView(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.conversationView.sizePolicy().hasHeightForWidth())
        self.conversationView.setSizePolicy(sizePolicy)
        self.conversationView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.conversationView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.conversationView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.conversationView.setObjectName(_fromUtf8("conversationView"))
        self.verticalLayout.addWidget(self.conversationView)
        self.verticalLayout.setStretch(0, 1)
        self.layoutWidget2 = QtGui.QWidget(self.splitterUpDown)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.peersView = QtGui.QTableView(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peersView.sizePolicy().hasHeightForWidth())
        self.peersView.setSizePolicy(sizePolicy)
        self.peersView.setBaseSize(QtCore.QSize(0, 0))
        self.peersView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.peersView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.peersView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.peersView.setObjectName(_fromUtf8("peersView"))
        self.verticalLayout_2.addWidget(self.peersView)
        self.verticalLayout_3.addWidget(self.splitterUpDown)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.newMessage = QtGui.QLineEdit(self.layoutWidget)
        self.newMessage.setObjectName(_fromUtf8("newMessage"))
        self.horizontalLayout.addWidget(self.newMessage)
        self.sendButton = QtGui.QPushButton(self.layoutWidget)
        self.sendButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.sendButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Gnome-Document-Send-64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon1)
        self.sendButton.setObjectName(_fromUtf8("sendButton"))
        self.horizontalLayout.addWidget(self.sendButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.logView = QtGui.QTextEdit(self.splitterLeftRight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logView.sizePolicy().hasHeightForWidth())
        self.logView.setSizePolicy(sizePolicy)
        self.logView.setMinimumSize(QtCore.QSize(0, 100))
        self.logView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logView.setReadOnly(True)
        self.logView.setObjectName(_fromUtf8("logView"))
        self.verticalLayout_4.addWidget(self.splitterLeftRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Messager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Conversation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Peers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

